import "./globals.css";
import { GlobalContextProvider } from "./context/store";
import ResponsiveAppBar from "./components/NavigationBar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="page-container">
          <div id="content-wrap">
            <ResponsiveAppBar />
            <GlobalContextProvider>{children}</GlobalContextProvider>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
